#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

echo "⏳ Provisioning IoT devices"
printf "    - IoT Devices are defined as \033[1mNGSI-v2\033[0m context data"

#
# Create a service groups for all UltraLight IoT devices
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "1068318794",
     "cbroker":     "http://orion:1026",
     "entity_type": "Motion",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name":"count", "type":"Integer"}
      ],
      "static_attributes": [
          {"name": "category", "type":"Text", "value": ["sensor"]},
          {"name": "controlledProperty", "type": "Text", "value": ["motion"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]},
          {"name": "supportedUnits", "type": "Text", "value": "C62"}
      ]
   },
   {
     "apikey":      "3020035",
     "cbroker":     "http://orion:1026",
     "entity_type": "Bell",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "commands": [ 
        {
          "name": "ring",
          "type": "command"
        }
      ],
      "static_attributes": [
          {"name": "category", "type":"Text", "value": ["actuator"]},
          {"name": "controlledProperty", "type": "Text", "value": ["noiseLevel"],
            "metadata":{
              "includes":{"type": "Text", "value" :["state", "dB"]},
              "alias":{"type": "Text", "value" :"bell"}
            }
          },
          {"name": "function", "type": "Text", "value":["ring"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]}
      ]
   },
   {
     "apikey":      "3314136",
     "cbroker":     "http://orion:1026",
     "entity_type": "Lamp",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "commands": [ 
        {"name": "on","type": "command"},
        {"name": "off","type": "command"}
     ],
     "attributes": [
        {"object_id": "s", "name": "state", "type":"Text",
          "metadata":{
              "unitCode":{"type": "Text", "value" :"CAL"}
          }
        },
        {"object_id": "l", "name": "luminosity", "type":"Integer"}
     ],
     "static_attributes": [
          {"name": "category", "type":"Text", "value": ["actuator","sensor"]},
          {"name": "controlledProperty", "type": "Text", "value": ["light"],
            "metadata":{
              "includes":{"type": "Text", "value" :["state", "luminosity"]},
              "alias":{"type": "Text", "value" :"lamp"}
            }
          },
          {"name": "function", "type": "Text", "value":["on", "off"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]},
          {"name": "supportedUnits", "type": "Text", "value": "CDL"}
     ]
   },
   {
     "apikey":      "3089326",
     "cbroker":     "http://orion:1026",
     "entity_type": "Door",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "Europe/Berlin",
     "commands": [ 
        {"name": "unlock","type": "command"},
        {"name": "open","type": "command"},
        {"name": "close","type": "command"},
        {"name": "lock","type": "command"}
      ],
     "attributes": [
        {"object_id": "s", "name": "door", "type":"Text"}
      ],
     "static_attributes": [
          {"name": "category", "type":"Text", "value": ["actuator", "sensor"]},
          {"name": "controlledProperty", "type": "Text", "value": ["door"]},
          {"name": "function", "type": "Text", "value":["unlock","lock","on","off"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]}
      ]
   }
 ]
}'

####################################################
#
# Provision sensors for Store 001
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "static_attributes": [
         {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store001"}
     ]
   },
   {
      "device_id": "bell001",
      "entity_name": "urn:ngsi-ld:Bell:001",
      "entity_type": "Bell",
      "endpoint": "http://iot-sensors:3001/iot/bell001",
      "static_attributes": [
          {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store001"}
      ]
    },
    {
      "device_id": "door001",
      "entity_name": "urn:ngsi-ld:Door:001",
      "entity_type": "Door",
      "endpoint": "http://iot-sensors:3001/iot/door001",
      "static_attributes": [
          {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store001"}
       ]
    }, 
    {
      "device_id": "lamp001",
      "entity_name": "urn:ngsi-ld:Lamp:001",
      "entity_type": "Lamp",
      "endpoint": "http://iot-sensors:3001/iot/lamp001",
      "static_attributes": [
          {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store001"}
      ]
    }
  ]
}
'

####################################################
#
#
# Provision sensors for Store 002
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion002",
     "entity_name": "urn:ngsi-ld:Motion:002",
     "entity_type": "Motion",
     "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store002"}
     ]
   },
   {
      "device_id": "bell002",
      "entity_name": "urn:ngsi-ld:Bell:002",
      "entity_type": "Bell",
      "endpoint": "http://iot-sensors:3001/iot/bell002",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store002"}
      ]
    },
    {
      "device_id": "door002",
      "entity_name": "urn:ngsi-ld:Door:002",
      "entity_type": "Door",
      "endpoint": "http://iot-sensors:3001/iot/door002",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store002"}
      ]
    },
    {
      "device_id": "lamp002",
      "entity_name": "urn:ngsi-ld:Lamp:002",
      "entity_type": "Lamp",
      "endpoint": "http://iot-sensors:3001/iot/lamp002",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store002"}
      ]
    }
  ]
}
'





####################################################
#
#
# Provision sensors for Store 3
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion003",
     "entity_name": "urn:ngsi-ld:Motion:003",
     "entity_type": "Motion",
     "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store003"}
     ]
   },
   {
      "device_id": "bell003",
      "entity_name": "urn:ngsi-ld:Bell:003",
      "entity_type": "Bell",
      "endpoint": "http://iot-sensors:3001/iot/bell003",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store003"}
      ]
    },
    {
      "device_id": "door003",
      "entity_name": "urn:ngsi-ld:Door:003",
      "entity_type": "Door",
      "endpoint": "http://iot-sensors:3001/iot/door003",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store003"}
      ]
    },
    {
      "device_id": "lamp003",
      "entity_name": "urn:ngsi-ld:Lamp:003",
      "entity_type": "Lamp",
      "endpoint": "http://iot-sensors:3001/iot/lamp003",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store003"}
      ]
    }
  ]
}
'




####################################################
#
#
# Provision sensors for Store 4
#

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion004",
     "entity_name": "urn:ngsi-ld:Motion:004",
     "entity_type": "Motion",
     "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store004"}
     ]
   },
   {
      "device_id": "bell004",
      "entity_name": "urn:ngsi-ld:Bell:004",
      "entity_type": "Bell",
      "endpoint": "http://iot-sensors:3001/iot/bell004",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store004"}
      ]
    },
    {
      "device_id": "door004",
      "entity_name": "urn:ngsi-ld:Door:004",
      "entity_type": "Door",
      "endpoint": "http://iot-sensors:3001/iot/door004",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store004"}
      ]
    },
    {
      "device_id": "lamp004",
      "entity_name": "urn:ngsi-ld:Lamp:004",
      "entity_type": "Lamp",
      "endpoint": "http://iot-sensors:3001/iot/lamp004",
      "static_attributes": [
        {"name": "controlledAsset", "type": "Relationship","value": "urn:ngsi-ld:Building:store004"}
      ]
    }
  ]
}
'

echo -e " \033[1;32mdone\033[0m"